Add solution for 0-module 2-task
js-tasks-ru/htmlcss-20210114_4e-olga pull request #2
Opened 2021-01-05 19:38 UTC by che-ola-la

2 task done

2021-01-05 20:39 UTC, PDmitryA requested changes
Привет!
Добро пожаловать на курс!

Давай поправим одно замечание по классам?) и еще один вопрос оставил, посмотри пожалуйста.

В целом хорошо получилось. Комментарии в html - огонь!

2021-01-05 20:39 UTC, diarmind commented on 01-intro/01-hello-world/solution.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
этот мета-тег здесь осознанно поставлен? расскажешь, что он делает?)

2021-01-05 20:39 UTC, PDmitryA commented on 02-dz0/01-semantic-mockup/styles.css
> +.navigation{
селекторы по классам и тегам лучше не смешивать.

для основного форматирования обычно применяют классы. 
когда сайт разрастается, то одинаковым тегам нужны разные стили.

хороший случай применения селекторов по тегам - если нужно выставить форматирование такому контенту, который создается пользователем. например, пользователь пишет статью в markdown, а затем ее автоматизированно переводим в html. Так сделано, например, на habrahabr.

давай всю стилизацию построим на селекторах по классу?

2021-01-05 21:16 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Hello world
+ вводная задача
```
```diff
Семантическая разметка страницы
+ семантическая разметка страницы
```

Добавляю преподавателя (@PDmitryA) для код-ревью, посмотрим что он скажет :)

2021-01-05 21:21 UTC, PDmitryA requested changes
чуть выше отписал)

2021-01-06 11:33 UTC, che-ola-la commented on 01-intro/01-hello-world/solution.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Первый мета устанавливает кодировку, второй мета - оптимизирует для мобильных устройств. 
В этом примере оставила, так как VS Code автоматически разворачивает такой шаблон html документа

2021-01-06 11:45 UTC, che-ola-la commented on 02-dz0/01-semantic-mockup/styles.css
> +.navigation{
Будет ли удачно использовать, например, для заголовка h2, который находится в блоке с классом .navigation вот такую конструкцию:
. nav h2{
     ...
}
Или лучше для заголовка h2 тоже добавить свой класс?

2021-01-06 14:13 UTC, PDmitryA commented on 02-dz0/01-semantic-mockup/styles.css
> +.navigation{
лучше свой класс

2021-01-06 19:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @PDmitryA

2021-01-06 20:35 UTC, PDmitryA requested changes
мне нравится! есть еще немножко минорных правок, и тогда смержим

нужна маленькая правка по тегу `link`.

и еще кое-что.
довольно часто в проектах заботятся о единообразии написанного кода.

так как у каждого стиль написания кода свой, линтера в задачнике нет. поэтому просьба поддерживать весь код плюс-минус в одном стиле, который тебе ближе)

1. в тегах иногда `attr = "value"`, иногда `attr="value"`
2. в css где-то есть отступы между селекторами по классам, где-то нет.

2021-01-06 20:35 UTC, PDmitryA commented on 02-dz0/01-semantic-mockup/solution.html
> +        <link rel="stylesheet" type="text/css" href="styles.css"
не хватает `>`

2021-01-07 08:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @PDmitryA

2021-01-07 08:41 UTC, PDmitryA approved these changes
отлично!

2021-01-07 08:41 UTC, merged